#!/bin/sh
set -e

# Set the colors of the boot-menu. Available colors are

#    black
#    blue
#    green
#    cyan
#    red
#    magenta
#    brown
#    light-gray
#    dark-gray
#    light-blue
#    light-green
#    light-cyan
#    light-red
#    light-magenta
#    yellow
#    white

echo "${1}set menu_color_normal=white/black"
echo "${1}set menu_color_highlight=black/light-gray"
